name: Update API Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir çalışır
  workflow_dispatch:        # Manuel tetikleme için
  push:
    branches: [ main ]     # Main branch'e push olduğunda da çalışır

permissions:
  contents: write
  pages: write
  id-token: write    # Bu satır eklendi

jobs:
  update-api:
    runs-on: ubuntu-latest
    
    # Environment ekledik
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci || npm install
          npm install axios
          npm install yaml

      - name: Create dist directory
        run: mkdir -p dist
        
      - name: Create cache directory
        run: mkdir -p .cache

      - name: Generate API data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/generate-api.js
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}